name: static check
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  gofmt:
    name: Ensure that code is gofmt-ed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@d1fab268ef4df10e7e11f248a179fedf9e94e054 # v1.1.0
      with:
        run: fmt
        comment: false
